apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80 # Outside world accesses it on port 80
      targetPort: 5000 # Forwards traffic to port 5000 in the container
  type: LoadBalancer # Exposes the app to the outside world (AWS, Google Cloud, or Azure)